-- V3: Dictionary table for planned operation activity types
-- (oględziny wizualne, skan 3D, lokalizacja awarii, zdjęcia, patrolowanie)

CREATE SEQUENCE FRU_DICT_ACTIVITY_TYPES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE FRU_DICT_ACTIVITY_TYPES (
    id   NUMBER        DEFAULT FRU_DICT_ACTIVITY_TYPES_SEQ.NEXTVAL NOT NULL,
    name VARCHAR2(100) NOT NULL,
    CONSTRAINT FRU_DICT_ACTIVITY_TYPES_PK PRIMARY KEY (id),
    CONSTRAINT FRU_DICT_ACTIVITY_TYPES_UK UNIQUE (name)
);
