-- V1: Dictionary table for crew member roles
-- (e.g. Pilot, Obserwator)

CREATE SEQUENCE FRU_DICT_CREW_ROLES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE FRU_DICT_CREW_ROLES (
    id   NUMBER        DEFAULT FRU_DICT_CREW_ROLES_SEQ.NEXTVAL NOT NULL,
    name VARCHAR2(100) NOT NULL,
    CONSTRAINT FRU_DICT_CREW_ROLES_PK PRIMARY KEY (id),
    CONSTRAINT FRU_DICT_CREW_ROLES_UK UNIQUE (name)
);
