-- V9: Landing sites table
-- Planned helicopter landing locations with coordinates

CREATE SEQUENCE FRU_LANDING_SITES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE FRU_LANDING_SITES (
    id         NUMBER               DEFAULT FRU_LANDING_SITES_SEQ.NEXTVAL NOT NULL,
    name       VARCHAR2(255)        NOT NULL,
    latitude   NUMBER(10, 7)        NOT NULL,
    longitude  NUMBER(10, 7)        NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FRU_LANDING_SITES_PK PRIMARY KEY (id),
    CONSTRAINT FRU_LS_LAT_CHK CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT FRU_LS_LON_CHK CHECK (longitude BETWEEN -180 AND 180)
);
